apply plugin: 'com.android.library'   // 先应用插件

android {
    compileSdkVersion 31

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 31
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

        externalNativeBuild {
            cmake {
                version "3.18.1"
                abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'
            }
        }
    }

    buildTypes {
        release {
            ndk { abiFilters "arm64-v8a", "armeabi-v7a", "x86", "x86_64" }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            ndk { abiFilters "arm64-v8a", "armeabi-v7a", "x86", "x86_64" }
        }
    }

    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
            version "3.18.1"
            arguments "-G", "Unix Makefiles"
        }
    }

    sourceSets {
        main {
            java.srcDirs 'src/main/java'
            jniLibs.srcDir 'src/main/libs'
        }
    }
}

// 最后再应用发布脚本
apply from: "../publish.gradle"

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])
    api 'androidx.appcompat:appcompat:1.4.1'
}
